import { ReactNode } from "react";

export const Pages: Record<string, () => ReactNode> = {
  "#intro": () => <div>Intro</div>,
  "#manuals-specifications": () => <div>Manuals Specifications</div>,
  "#code-editors": () => <div>Code Editors</div>,
  "#devtools": () => <div>Developer Console</div>,
  "#hello-world": () => <div>Hello World</div>,
  "#structure": () => <div>Structure</div>,
  "#strict-mode": () => <div>Strict Mode</div>,
  "#variables": () => <div>Variables</div>,
  "#types": () => <div>Data Types</div>,
  "#alert-prompt-confirm": () => <div>Alert, Prompt, Confirm</div>,
  "#type-conversions": () => <div>Type Conversions</div>,
  "#operators": () => <div>Operators</div>,
  "#comparison": () => <div>Comparisons</div>,
  "#ifelse": () => <div>If Else</div>,
  "#logical-operators": () => <div>Logical Operators</div>,
  "#nullish-coalescing-operator": () => <div>Nullish Coalescing Operator</div>,
  "#while-for": () => <div>While and For Loops</div>,
  "#switch": () => <div>Switch</div>,
  "#function-basics": () => <div>Functions</div>,
  "#function-expressions": () => <div>Function Expressions</div>,
  "#arrow-functions-basics": () => <div>Arrow Functions</div>,
  "#javascript-specials": () => <div>JavaScript Specials</div>,
  "#debugging": () => <div>Debugging in Chrome</div>,
  "#coding-style": () => <div>Coding Style</div>,
  "#comments": () => <div>Comments</div>,
  "#ninja-code": () => <div>Ninja Code</div>,
  "#testing-mocha": () => <div>Testing</div>,
  "#polyfills": () => <div>Polyfills</div>,
  "#object": () => <div>Object Methods</div>,
  "#object-copy": () => <div>Object References</div>,
  "#garbage-collection": () => <div>Garbage Collection</div>,
  "#object-methods": () => <div>Object Methods</div>,
  "#constructor-new": () => <div>Constructor, Operator New</div>,
  "#optional-chaining": () => <div>Optional Chaining</div>,
  "#symbol": () => <div>Symbol Type</div>,
  "#object-to-primitive": () => <div>Object to Primitive</div>,
};
